### ISSUE TITLE
Better describe what gulp is on the homepage

### ISSUE THREAD

**Issue by phated** [gulpjs/gulpjs.github.io#54]
This should probably be above the fold unless it ends up being multiple bullet points.

I wanted to open this issue so we can discuss what this should say and look like.

Ref #39

**Comment by CKGrafico** [comment]
I think that for a regular dev the mockup that you post on the other issue is really nice. For a beginner could be not enough as you said before.

When I try to explain what is gulp or what is a task runner to a newbie I start telling to them that is like a program that help's me doing the things that I don't want to do.
- Hey Quique, you've added a new image I will compress it for you.
- Hey Quique, you've added new code, be careful your tests failed.

etc..

Can be a point to start xD

**Comment by Mordax** [comment]
Mind if I help out? No experience with Gulp, barely touched Node.js and recently new in the Open source world (but I have been programming for quite some time). 

Incoming giant block of text - let me know if anything needs clarification (it's midnight and I'm both energized and half asleep).

I've been reading through the various [articles](https://github.com/gulpjs/gulp/blob/master/docs/README.md#articles) provided and it took me basically an hour to finally understand what Gulp is (I have very basic knowledge on tooling, like automating using package.json, ESLint, etc, but it was still hard). 

This [link](https://markgoodyear.com/2014/01/getting-started-with-gulp/) helped the most, but it assumes the reader knows what Grunt is. 

`I took away the following ideas from reading most of the articles (* denotes that I had to look it up):`

- Gulp automates any task the programmer wants -  you can code your own if you want.
- There are lots of gulp specific plugins* and you can use all of the node packages as well. 
- It strives to be an all-in-one place for these tasks so you don't have to keep installing or configuring different task programs.
- Gulp is different from Grunt* in that it uses streams* (If I didn't know pipes from Bash scripting, this would confuse me). 
- It connects to different "task plugins" without configuring each one separately. You can also do 200 tasks using 1 command and it just gets passed to each plugin without any problem.
- Gulp is different from Grunt because it does all of this faster without being a resource hog. Instead of the code that was modified by a task being saved and sent to the next task*, then saved, then sent, etc, the stream doesn't save the modified code, it just pipes it to the next task (basically in RAM) and only when you're done all the tasks, does it get saved. 

If my understanding is incorrect or I missed another important Gulp feature, please let me know. 

I think the assumption of the beginner programmer should be that they have basic knowledge of a terminal and understand basic ideas such as syntax errors. Obviously if they don't have experience with Node, they won't be able to use it, but it should entice them to check it out at least.

Quique's explanation that it "helps me do the things I don't want to do" was a bit too vague for me, and regarding the examples, I think just saying "I will check your code for errors, I will test your code - oops it failed, etc" might be better. The "you've added a new image, you've added new code" sounds like Gulp does this in real time as you're programming rather than when you call the Gulp command. 

I'm certainly interested in using Gulp now - I think I'll try it out in future Node projects to come. Hopefully future users will hop to using it right away with less research needed. :D

**Comment by ocelotluke** [comment]
I wrote up a little description of what I would describe Gulp as. There are a few things that could be improved, like changing the examples of what it could be used for (this is based on my workflow, maybe a more diverse range of use cases would be better) & possibly beefing out the second paragraph, but I think this is a fairly good fist draft of what you are looking for: 

>Gulp is a build tool that automates and enhances your workflow so you can spend more time developing & less time carrying out build tasks such as: compiling CSS, minifying JavaScript and compressing images. 
>
>With thousands of pre-approved plugins, maximum concurrency & a shallow learning curve Gulp can save you hundreds of hours.  
>
>Please follow our Getting Started guide, then head over to the plugins directory to find out which tasks can be automated by Gulp in your workflow…
>
>[get started button]

Let me know what you think / how it can be improved / if you hate it or not 👍

**Comment by tumulr** [comment]
Since this issue is still open, I would like to say how about one adds a small video about what gulp does. The reason being gulp does a lot of things and if we write about it, it will be a long description.

@phated What are your thoughts on the above idea?

**Comment by phated** [comment]
Nah to the video

**Comment by phated** [comment]
This is done! We revamped all the copy on the brand new website!
